-- iris: online_safe=true lock_ms=200 min_app=0.12.0 max_app= recovery=none
-- Console keyset reads: additive indexes, no changes to Canonical content.
CREATE INDEX idx_console_observations_created ON observations (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_state_records_created ON state_records (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_state_record_revisions_created ON state_record_revisions (record_id, created_us DESC, id DESC);
CREATE INDEX idx_console_focus_items_created ON focus_items (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_focus_item_revisions_created ON focus_item_revisions (item_id, created_us DESC, id DESC);
CREATE INDEX idx_console_notes_created ON notes (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_note_revisions_created ON note_revisions (note_id, created_us DESC, id DESC);
CREATE INDEX idx_console_tasks_created ON tasks (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_task_revisions_created ON task_revisions (task_id, created_us DESC, id DESC);
CREATE INDEX idx_console_claims_created ON claims (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_claim_revisions_created ON claim_revisions (claim_id, created_us DESC, id DESC);
CREATE INDEX idx_console_episodes_created ON episodes (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_episode_revisions_created ON episode_revisions (episode_id, created_us DESC, id DESC);
CREATE INDEX idx_console_relations_created ON relations (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_relation_revisions_created ON relation_revisions (relation_id, created_us DESC, id DESC);
CREATE INDEX idx_console_artifacts_created ON artifacts (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_entities_created ON entities (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_entity_revisions_created ON entity_revisions (entity_id, created_us DESC, id DESC);
CREATE INDEX idx_console_external_identities_created ON external_identities (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_bindings_created ON bindings (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_binding_revisions_created ON binding_revisions (binding_id, created_us DESC, id DESC);
CREATE INDEX idx_console_cognitive_events_created ON cognitive_events (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_cognitive_event_revisions_created ON cognitive_event_revisions (event_id, created_us DESC, id DESC);
CREATE INDEX idx_console_reflection_records_created ON reflection_records (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_cognitive_candidates_created ON cognitive_candidates (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_agents_created ON agents (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_space_groups_created ON space_groups (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_spaces_created ON spaces (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_sessions_created ON sessions (tenant_id, started_us DESC, id DESC);
CREATE INDEX idx_console_task_steps_created ON task_steps (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_task_step_revisions_created ON task_step_revisions (step_id, created_us DESC, id DESC);
CREATE INDEX idx_console_task_dependencies_created ON task_dependencies (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_task_dependency_revisions_created ON task_dependency_revisions (dependency_id, created_us DESC, id DESC);
CREATE INDEX idx_console_task_triggers_created ON task_triggers (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_task_trigger_revisions_created ON task_trigger_revisions (trigger_id, created_us DESC, id DESC);
CREATE INDEX idx_console_persona_revisions_created ON persona_revisions (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_persona_proposals_created ON persona_proposals (tenant_id, created_us DESC, id DESC);
CREATE INDEX idx_console_links_source ON resource_links (tenant_id, source_type, source_id, created_us DESC, id DESC);
CREATE INDEX idx_console_links_target ON resource_links (tenant_id, target_type, target_id, created_us DESC, id DESC);
