"""Current reviewed persona through one native, bounded local read capability.

The source owner checks actual SELF revision; a stale publication is visible and
never regenerated by reading. Delivery and short-transaction verification use
the existing runtime publication fence and retain their actual read consumers.
"""
from __future__ import annotations
import asyncio
import time
from dataclasses import dataclass
from types import MappingProxyType
from companion_memory.persistence import UnitOfWork,Value
from companion_memory.persistence.completion import finish_owned,retain_completion
from companion_memory.persistence.deadlines import DeadlineScope
from companion_memory.persistence.owned_statements import OwnerFailure
from companion_memory.persistence.schema import InvalidValue,valid_identifier
from .results import rejected,owner_failure
from .transactions import PersonaTransactions
from .formats import projection


@dataclass(frozen=True,slots=True)
class Available:
    value: MappingProxyType[str,Value]


@dataclass(frozen=True,slots=True)
class Unavailable:
    pass


@dataclass(frozen=True,slots=True)
class Matched:
    value: MappingProxyType[str,Value]


@dataclass(frozen=True,slots=True)
class Conflict:
    pass


@dataclass(frozen=True,slots=True,init=False)
class CurrentPersonaPort:
    """Current-only read authority; no history, generation, review or publication."""
    _owner: CurrentPersona
    def __init__(self):raise TypeError('Current persona authority is issued by trusted setup.')
    async def read_current(self,deadline: float):
        owner=getattr(self,'_owner',None)
        if type(self) is not CurrentPersonaPort or type(owner) is not CurrentPersona or owner.port is not self:
            return rejected('read_current','boundary')
        return await owner.read(deadline)
    def verify_current(self,uow: UnitOfWork,publication_id: str,expected_revision: int):
        owner=getattr(self,'_owner',None)
        if type(self) is not CurrentPersonaPort or type(owner) is not CurrentPersona or owner.port is not self:
            return rejected('verify_current','boundary')
        return owner.verify(uow,publication_id,expected_revision)


class CurrentPersona:
    """The sole first-persona read owner, sharing existing source storage leases."""
    def __init__(self,transactions: PersonaTransactions):
        if type(transactions) is not PersonaTransactions or transactions.persona is None or transactions.initial is None or transactions.gate is None:raise InvalidValue()
        self.transactions=transactions;self._closed=False;self._task:asyncio.Task|None=None
        port=object.__new__(CurrentPersonaPort);object.__setattr__(port,'_owner',self);self.port=port

    def _checkpoint(self):
        t=self.transactions
        if self._closed or t._closed or t.gate is None:raise OwnerFailure('INVALID_STATE','state','SERVICE_CLOSED')
        checkpoint=t.gate.information_checkpoint()
        if checkpoint is None:
            if t.gate.information_operation_reason() is None:raise OwnerFailure('RESOURCE_BUSY','resource','CLEANUP_PENDING',True)
            raise OwnerFailure('MODE_BLOCKED','state','DREAMING')
        return checkpoint

    async def read(self,deadline: float):
        operation='read_current';t=self.transactions
        if type(deadline) not in (float,int) or not time.monotonic()<deadline<float('inf'):return rejected(operation,'shape')
        try:
            checkpoint=self._checkpoint()
            if self._task is not None:raise OwnerFailure('RESOURCE_BUSY','resource','CLEANUP_PENDING',True)
            async def inspect():
                assert t.persona is not None and t.initial is not None and t.gate is not None
                with DeadlineScope(deadline):
                    found=await t.persona.current_original(deadline)
                    value=Unavailable() if found is None else Available(projection(found.value,
                        await t.initial.publication_stale_original(found.value,deadline)))
                    delivered=[]
                    if (time.monotonic()>=deadline or not t.gate.start_information_delivery(checkpoint,
                            lambda:not self._closed and not t._closed,lambda:delivered.append(value))):
                        self._checkpoint()
                        if time.monotonic()>=deadline:raise OwnerFailure('RESOURCE_BUSY','resource','CLEANUP_PENDING')
                        raise OwnerFailure('PRECONDITION_FAILED','revision','REVISION_CONFLICT')
                    return delivered[0]
            task=asyncio.create_task(finish_owned(inspect()));self._task=task;retain_completion(task)
            def ended(job):
                if not job.cancelled():job.exception()
                if self._task is job:self._task=None
            task.add_done_callback(ended)
            done,_=await asyncio.wait((task,),timeout=max(0,deadline-time.monotonic()))
            if not done:return rejected(operation,'busy',True)
            return task.result()
        except OwnerFailure as failure:return owner_failure(operation,failure)
        except (InvalidValue,KeyError,TypeError):return rejected(operation,'record')

    def verify(self,uow: UnitOfWork,publication_id: str,expected_revision: int):
        operation='verify_current';t=self.transactions
        if not valid_identifier(publication_id) or type(expected_revision) is not int or expected_revision<1:return rejected(operation,'shape')
        try:
            assert t.persona is not None and t.initial is not None and t.gate is not None
            gate=t.gate
            # SQLite already serializes the complete source/publication read
            # with the enclosing commit. Unrelated index writers may withdraw
            # query delivery, but cannot invalidate this transaction's persona.
            with gate.lock:
                if self._closed or t._closed or gate.information_operation_reason() is not None:
                    raise OwnerFailure('PRECONDITION_FAILED','state','STATE_MISMATCH')
                epoch=gate.epoch
            current=t.persona.current_publication(uow)
            if current is None or (current.value['object_id'],current.value['revision'])!=(publication_id,expected_revision):return Conflict()
            value=projection(current.value,t.initial.publication_stale(uow,current.value))
            uow.require_commit_permission(lambda:not self._closed and not t._closed and gate.epoch==epoch and gate.information_operation_reason() is None)
            return Matched(value)
        except OwnerFailure as failure:return owner_failure(operation,failure)
        except (InvalidValue,KeyError,TypeError):return rejected(operation,'record')

    async def close(self,deadline: float) -> bool:
        """Withdraw delivery before joining only this owner's actual pending reads."""
        self._closed=True
        if self._task is None:return True
        done,_=await asyncio.wait((self._task,),timeout=max(0,deadline-time.monotonic()))
        return bool(done)
