-- Scene events have their own fixed subject. The v1 sender was incorrectly self.
INSERT OR IGNORE INTO subjects(id,kind,name,created_at)
VALUES('scene','person','场景',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
UPDATE messages SET sender_subject_id='scene' WHERE kind='event';

-- Goals generated by learning are scoped to the entry whose messages created them.
ALTER TABLE goals ADD COLUMN entry_id TEXT REFERENCES entries(id);
UPDATE goals SET entry_id=(
    SELECT m.entry_id FROM goal_sources gs
    JOIN messages m ON m.id=gs.message_id
    WHERE gs.goal_id=goals.id ORDER BY gs.message_id LIMIT 1
);
CREATE INDEX goals_open_by_entry ON goals(entry_id,kind,state);
