"""Reviewed client-to-operation mapping; additions require an explicit policy edit."""

# These are named SDK operations, not a traversal of the implementation package.
PYTHON_OPERATIONS: dict[str, tuple[str, ...]] = {
    "capabilities": ("getCapabilities",),
    "negotiate": ("negotiateCapabilities",),
    "observation_context": ("readObservationContext",),
    "summarize_observations": ("summarizeObservationContext",),
    "observe_batch": ("observeBatch",),
    "source_cursor": ("getSourceCursor",),
    "acquire_surface_lease": ("acquireSurfaceLease",),
    "heartbeat_surface_lease": ("heartbeatSurfaceLease",),
    "release_surface_lease": ("releaseSurfaceLease",),
    "current_surface_lease": ("getCurrentSurfaceLease",),
    "recent_context": ("getRecentContext",),
    "put_state": ("putState",),
    "get_state": ("getState",),
    "list_states": ("listStates",),
    "state_history": ("getStateHistory",),
    "create_focus_item": ("createFocusItem",),
    "get_focus_item": ("getFocusItem",),
    "list_focus_items": ("listFocusItems",),
    "focus_transition": (
        "activateFocusItem",
        "setFocusDormant",
        "dismissFocusItem",
        "expireFocusItem",
        "promoteFocusItem",
    ),
    "rebuild_recent_context": ("rebuildRecentContext",),
    "create_note": ("createNote",),
    "list_notes": ("listNotes",),
    "update_note": ("updateNote",),
    "note_action": ("archiveNote", "promoteNote"),
    "create_task": ("createTask",),
    "list_tasks": ("listTasks",),
    "update_task": ("updateTask",),
    "transition_task": ("transitionTask",),
    "create_task_step": ("createTaskStep",),
    "transition_task_step": ("transitionTaskStep",),
    "create_task_dependency": ("createTaskDependency",),
    "create_task_trigger": ("createTaskTrigger",),
    "list_cognitive_events": ("listCognitiveEvents",),
    "ack_cognitive_event": ("ackCognitiveEvent",),
    "remember_claim": ("createClaimRemember",),
    "correct_claim": ("correctClaim",),
    "get_claim": ("getClaim",),
    "search_claims": ("searchClaims",),
    "claim_history": ("claimHistory",),
    "forget_memory": ("forgetMemory",),
    "create_episode": ("createEpisode",),
    "transition_episode": ("transitionEpisode",),
    "get_episode": ("getEpisode",),
    "create_relation": ("createRelation",),
    "get_relation": ("getRelation",),
    "create_artifact": ("createArtifact",),
    "get_artifact": ("getArtifact",),
    "set_retention_policy": ("setRetentionPolicy",),
    "list_retention_policies": ("listRetentionPolicies",),
    "create_legal_hold": ("createLegalHold",),
    "release_legal_hold": ("releaseLegalHold",),
    "export_deletion_ledger": ("exportDeletionLedger",),
    "readiness": ("getReadiness",),
    "list_admin_jobs": ("listAdminJobs",),
    "retry_admin_job": ("replayDeadLetter",),
    "create_schedule": ("createSchedule",),
    "run_schedule_now": ("runScheduleNow",),
    "recall": ("recall",),
    "report_recall_usage": ("reportRecallUsage",),
    "search": ("search",),
    "current_persona": ("getCurrentPersona",),
    "persona_history": ("getPersonaHistory",),
    "publish_persona_revision": ("publishPersonaRevision",),
    "update_persona_state": ("updatePersonaState",),
    "create_persona_proposal": ("createPersonaEvolutionProposal",),
    "review_persona_proposal": (
        "approvePersonaEvolutionProposal",
        "rejectPersonaEvolutionProposal",
    ),
    "rollback_persona": ("rollbackPersona",),
    "get_entity_profile": ("getEntityProfile",),
    "get_entity": ("getEntity",),
    "get_entity_relations": ("getEntityRelations",),
    "create_identity": ("createIdentity",),
    "prepare_binding": ("prepareBinding",),
    "review_binding": ("confirmBinding", "revokeBinding"),
    "list_space_groups": ("listSpaceGroups",),
    "create_space_group": ("createSpaceGroup",),
    "set_space_group_binding": ("bindSpaceGroup", "unbindSpaceGroup"),
    "rebuild_index": ("rebuildIndex",),
    "create_backup": ("createBackup",),
    "create_export": ("createExport",),
    "list_audit_events": ("listAuditEvents",),
    "dry_run_reflection": ("dryRunReflection",),
    "replay_reflection": ("replayReflection",),
}

CORE_EXPORTS = ("__version__",)
SDK_EXPORTS = (
    "AsyncIrisMemoryClient",
    "CapabilitiesEnvelope",
    "ContractValidationError",
    "ErrorEnvelope",
    "validate_contract",
)
SDK_MODULE_SYMBOLS = {
    "iris_memory_sdk.client": (
        "AsyncIrisMemoryClient",
        "IrisMemoryApiError",
        "IrisMemoryTransportError",
    ),
    "iris_memory_sdk.models": (
        "CapabilitiesEnvelope",
        "ContractValidationError",
        "ErrorEnvelope",
        "validate_contract",
    ),
}

# Lifecycle methods do not correspond to HTTP operations.
PYTHON_LIFECYCLE = ("aclose",)
