/** External connection forms consume authenticated native management facts. */
import type {ConfigurationOperation} from './configuration_operation.js';
type Row=Record<string,unknown>;
type Context={configuration:ConfigurationOperation;page:HTMLElement;api:(path:string,payload?:Row)=>Promise<unknown>;object:(v:unknown)=>Row;escape:(v:unknown)=>string;show:(s:string,error?:boolean)=>void;bind:(id:string,work:(f:HTMLFormElement)=>Promise<void>)=>void;write:(name:string,path:string,input:Row,keyField?:string)=>Promise<Row>};
let browserSocket:WebSocket|undefined;
export function closeConnectionPage():void {browserSocket?.close(1000,'PAGE_CLOSED');browserSocket=undefined;}
export async function renderConnections(c:Context,tab='overview'):Promise<void>{
  c.page.setAttribute('aria-busy','true');
  try {
  closeConnectionPage();
  const {page,api,object,escape:esc,show,bind,write,configuration}=c;
  const overview=object(await api('/api/connections/overview',{}));
  const routes=(overview.routes as unknown[]).map(object);
  const connections=(overview.connections as unknown[]).map(object);
  const tabs=[['overview','连接概览'],['hosts','宿主与入口'],['tokens','凭据与权限'],['routes','通知路由'],['deliveries','连接与投递'],['settings','通信设置'],['testing','接入说明与联调']];
  const field=(label:string,name:string,required=true)=>`<label>${label}<input name="${name}" maxlength="128" ${required?'required':''}></label>`;
  const selectRoutes=(name='route_id')=>`<label>通知路由<select aria-label="通知路由" name="${name}" required><option value="">选择路由</option>${routes.map(r=>`<option value="${esc(r.object_id)}">${esc(r.object_id)} · ${esc(r.host_id)} · ${r.enabled?'已启用':'已禁用'} · ${r.online?'在线':'离线'}</option>`).join('')}</select></label>`;
  const val=(f:HTMLFormElement,name:string)=>String(new FormData(f).get(name)??'');
  const values=(f:HTMLFormElement,name:string)=>new FormData(f).getAll(name).map(String);
  const summary=(row:unknown)=>`<pre>${esc(JSON.stringify(row,null,2))}</pre>`;
  const checks=(name:string,items:string[])=>items.map(item=>`<label class="check"><input type="checkbox" name="${name}" value="${esc(item)}">${esc(item)}</label>`).join('');
  page.innerHTML=`<h1 tabindex="-1">外部连接</h1><nav class="actions" aria-label="外部连接页面">${tabs.map(([id,label])=>`<button type="button" data-connection-tab="${id}" ${id===tab?'aria-current="page"':''}>${label}</button>`).join('')}</nav><div id="connection-panel"></div>`;
  for(const button of page.querySelectorAll<HTMLButtonElement>('[data-connection-tab]'))button.onclick=()=>{void renderConnections(c,button.dataset.connectionTab).then(()=>page.querySelector<HTMLButtonElement>('[data-connection-tab][aria-current="page"]')?.focus()).catch(e=>show(String(e),true));};
  const area=page.querySelector<HTMLElement>('#connection-panel')!;
  async function refresh(){await renderConnections(c,tab);page.querySelector<HTMLElement>('h1')?.focus();}
  async function list(path:string,title:string,render?:(r:Row)=>string):Promise<void>{
    const container=document.createElement('section');container.className='card';container.innerHTML=`<h2>${title}</h2><div class="items"></div><button type="button">读取下一页</button>`;area.append(container);
    let after='';let busy=false;
    const button=container.querySelector<HTMLButtonElement>('button')!;
    async function read(){if(busy)return;busy=true;button.disabled=true;try{const result=object(await api(path,{after}));const items=(result.items as unknown[]).map(object);if(!items.length&&!after)container.querySelector('.items')!.textContent='暂无记录。';for(const row of items){const card=document.createElement('article');card.className='card';card.innerHTML=render?render(row):summary(row);container.querySelector('.items')!.append(card);}after=String(result.after??'');button.disabled=!after;}finally{busy=false;}}
    button.onclick=()=>{void read().catch(e=>show(String(e),true));};await read();
  }
  if(tab==='overview'){
    area.innerHTML=`<section class="card"><h2>${overview.ws_available?'WS 可接入':overview.ws_enabled?'WS 暂不可接入':'WS 已禁用'}</h2><p>当前模式：${esc(overview.mode)}；${overview.notifications_paused?'新通知已暂停':'按已启用路由派发'}。在线不代表当前可以发送。</p><p>HTTP：${esc(overview.origin)}</p><p>WS：${esc(String(overview.origin).replace(/^http/,'ws'))}/api/host/ws</p><p>协议：${esc(overview.subprotocol)}</p><p>实际配置：${esc(overview.configuration_id)}</p><p>消费者 ${connections.length} 个，可信路由 ${routes.length} 条。</p></section><section class="card"><h2>首次接入</h2><ol><li>完成初始化，登记宿主和入口。</li><li>创建路由，签发限定权限令牌。</li><li>在通信设置启用 WS，运行客户端并订阅。</li><li>明确启用路由，发送合成探针。</li><li>在目标管理页选择路由并创建有期限目标。</li></ol></section><section class="card"><h2>断线诊断</h2><p>查看连接、心跳及投递事实。修复宿主后，用原身份重新认证并显式接管所需路由，再查询当前目标。UNKNOWN 不允许重发；其他路由的订阅继续有效。</p></section>`;
  }else if(tab==='hosts'){
    area.innerHTML=`<form id="connection-host" class="card"><h2>登记合法入口</h2>${field('宿主标识','host_id')}${field('入口标识','entry_id')}${field('已有平台标识','platform_id')}${field('外部会话标识','external_entry_id')}<p>仅绑定已配置平台；已引用的宿主和入口标识不可改写。</p><button>确认登记</button></form>`;
    bind('#connection-host',async f=>{await write('connection.host','/api/connections/hosts/register',Object.fromEntries(['host_id','entry_id','platform_id','external_entry_id'].map(n=>[n,val(f,n)])));await refresh();});
    await list('/api/connections/hosts/list','登记事实');
  }else if(tab==='tokens'){
    const entryRows:Row[]=[];let after='';do{const r=object(await api('/api/connections/hosts/list',{after}));entryRows.push(...(r.items as unknown[]).map(object));after=String(r.after??'');}while(after&&entryRows.length<64);
    const operations=[['接收与媒体','accept','media_upload','media_inspect'],['召回与反馈','prepare','query','deep_recall','feedback'],['状态','state_read','state_write'],['目标','goal_read','goal_write'],['通知与观察','notifications','runtime_observe','probe'],['原操作','confirm']];
    area.innerHTML=`<form id="connection-token" class="card"><h2>签发有限权限令牌</h2><label>宿主<select aria-label="宿主" name="host_id">${[...new Set(entryRows.map(r=>String(r.host_id)))].map(h=>`<option>${esc(h)}</option>`).join('')}</select></label><fieldset><legend>入口多选</legend>${checks('entries',entryRows.map(r=>String(r.entry_id)))}</fieldset>${operations.map(([title,...ops])=>`<fieldset><legend>${title}</legend>${checks('operations',ops)}</fieldset>`).join('')}<fieldset><legend>允许路由</legend>${checks('route_ids',routes.map(r=>String(r.object_id)))}</fieldset><fieldset><legend>允许事件</legend>${checks('event_types',['goal.upcoming','goal.due','core.mode_changed','connection.probe'])}</fieldset><label>有效期（小时）<input name="hours" type="number" min="1" max="720" value="24" required></label><p>新令牌只显示一次。轮换时先签发新令牌、按所需路由接管，再撤销旧令牌。</p><button>签发令牌</button><div id="connection-secret" aria-live="polite"></div></form>`;
    let submitted:Row|undefined;
    bind('#connection-token',async f=>{submitted??={key:crypto.randomUUID(),host_id:val(f,'host_id'),entries:values(f,'entries'),operations:values(f,'operations'),route_ids:values(f,'route_ids'),event_types:values(f,'event_types'),expires_at_us:(Date.now()+Number(val(f,'hours'))*3600000)*1000};const result=object(await api('/api/tokens/create',submitted));page.querySelector('#connection-secret')!.textContent=result.token?`请立即安全保存：${String(result.token)}`:'原签发已确认；秘密无法重新显示。请撤销后重新签发。';});
    await list('/api/tokens/list','凭据状态',r=>`<p>${esc(r.host_id)} · ${esc(r.state)} · ${esc(r.operations)}</p>${summary(r)}<button type="button" data-revoke="${esc(r.object_id)}" data-revision="${r.revision}" ${r.revoked?'disabled':''}>撤销令牌</button>`);
    area.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-revoke]');if(b){b.disabled=true;void write('connection.revoke.'+b.dataset.revoke,'/api/tokens/revoke',{token_id:b.dataset.revoke,expected_revision:Number(b.dataset.revision)}).then(refresh).catch(e=>{b.disabled=false;show(String(e),true);});}});
  }else if(tab==='routes'){
    area.innerHTML=`<form id="connection-route" class="card"><h2>新建通知路由</h2>${field('路由标识','route_id')}${field('宿主标识','host_id')}<label>入口（逗号分隔）<input name="entries" required></label><fieldset><legend>允许事件</legend>${checks('event_types',['goal.upcoming','goal.due','core.mode_changed','connection.probe'])}</fieldset><button>创建禁用路由</button></form>${routes.map(r=>`<section class="card"><h2>${esc(r.object_id)}</h2><p>${esc(r.host_id)} · ${esc(r.entries)} · 未结束目标 ${r.open_goals} · 修订 ${r.revision} · ${r.enabled?'已启用':'已禁用'} · ${r.online?'在线':'离线：目标可保存，提醒可能无法送达'}</p><button type="button" data-route="${esc(r.object_id)}">${r.enabled?'禁用':'启用'}此路由</button></section>`).join('')}`;
    bind('#connection-route',async f=>{await write('connection.route','/api/connections/routes/create',{route_id:val(f,'route_id'),host_id:val(f,'host_id'),entries:val(f,'entries').split(',').map(x=>x.trim()),event_types:values(f,'event_types')});await refresh();});
    for(const b of area.querySelectorAll<HTMLButtonElement>('[data-route]'))b.onclick=()=>{const r=routes.find(r=>r.object_id===b.dataset.route)!;b.disabled=true;void write('connection.route.'+r.object_id,'/api/connections/routes/enable',{route_id:r.object_id,expected_revision:r.revision,enabled:!r.enabled}).then(refresh).catch(e=>{b.disabled=false;show(String(e),true);});};
  }else if(tab==='deliveries'){
    area.innerHTML=`<section class="card"><h2>当前连接</h2><p>观察时间：${esc(new Date(Number(overview.observed_at_us)/1000).toISOString())}。等待 ACK、持久确认、UNKNOWN 与清理状态分别显示。</p>${connections.length?'':'暂无在线连接。'}${connections.map(r=>`<article>${summary(r)}<form data-disconnect="${esc(r.connection_id)}"><label class="check"><input type="checkbox" required>确认断开此连接的全部上述订阅</label><button>安全断开</button></form></article>`).join('')}</section><section class="card"><h2>当前投递</h2>${summary(overview.deliveries)}<h2>按路由接管</h2>${summary(overview.takeovers)}</section>`;
    for(const f of area.querySelectorAll<HTMLFormElement>('[data-disconnect]')){f.onsubmit=e=>{e.preventDefault();const r=connections.find(r=>r.connection_id===f.dataset.disconnect)!;void api('/api/connections/connections/disconnect',{connection_id:r.connection_id,route_ids:(r.subscriptions as Row[]).map(s=>s.route_id)}).then(refresh).catch(e=>show(String(e),true));};}
    area.insertAdjacentHTML('beforeend',`<form id="connection-plans" class="card"><h2>计划与宽限</h2>${selectRoutes()}<button>读取计划</button></form><div id="connection-plan-results"></div><button type="button" id="connection-plan-more" disabled>下一页计划</button>`);
    let planAfter='';let planRoute='';const more=page.querySelector<HTMLButtonElement>('#connection-plan-more')!;
    async function readPlans(){const result=object(await api('/api/connections/plans/list',{route_id:planRoute,after:planAfter}));page.querySelector('#connection-plan-results')!.insertAdjacentHTML('beforeend',summary(result));planAfter=String(result.after??'');more.disabled=!planAfter;}
    bind('#connection-plans',async f=>{planRoute=val(f,'route_id');planAfter='';page.querySelector('#connection-plan-results')!.replaceChildren();await readPlans();});more.onclick=()=>{more.disabled=true;void readPlans().catch(e=>show(String(e),true));};
    await list('/api/connections/probes/list','探针最近事实与累计核账');
  }else if(tab==='settings'){
    const active=object(await api('/api/configuration/read',{version_id:null}));const state=object(active.status);
    const policy=structuredClone(object(overview.policy));
    area.innerHTML=`<form id="connection-settings" class="card"><h2>通信配置</h2><p>实际版本：${esc(active.version_id)}；状态：${esc(state.state)}。固定小档的容量、心跳及宽限一起验证。</p><label class="check"><input type="checkbox" name="enabled" ${object(policy['communication.ws']).enabled?'checked':''}>允许 WS 接入</label><label>目标提醒<select aria-label="目标提醒" name="sink"><option value="DISABLED">禁用</option><option value="WS" ${object(policy['communication.delivery']).sink_mode==='WS'?'selected':''}>WS</option></select></label><details><summary>实际完整参数</summary>${summary(policy)}</details><details><summary>默认参数与合法范围</summary>${summary(overview.defaults)}${summary(overview.configuration_schema)}</details><p>外部地址 ${esc(overview.origin)}；地址和代理来源由部署方受控重启生效。</p><button>验证并预览影响</button></form><div id="connection-preview"></div>`;
    async function finishConfiguration(work:()=>Promise<string>):Promise<void>{
      let result:string;
      try{result=await work();}catch(error){await refresh();throw error;}
      await refresh();show(result==='PREPARATION_FAILED'?'资源准备失败，原有效配置继续使用。':result==='SUPERSEDED'?'原配置已被更新版本替代。':'配置已由实际消费者接入。',result==='PREPARATION_FAILED');
    }
    if(configuration.pending()){
      area.querySelector<HTMLFormElement>('#connection-settings')!.hidden=true;
      area.insertAdjacentHTML('beforeend','<form id="connection-configuration-resume" class="card"><h2>有一项待确认操作</h2><p>原配置请求和激活标识已保留。完成前暂不发起另一项配置修改。</p><button>继续原配置操作</button></form>');
      bind('#connection-configuration-resume',async()=>finishConfiguration(()=>configuration.resume()));
    }
    bind('#connection-settings',async f=>{object(policy['communication.ws']).enabled=new FormData(f).has('enabled');object(policy['communication.delivery']).sink_mode=val(f,'sink');const input={expected_revision:state.revision,patch:{text:policy}};const plan=object(await api('/api/configuration/preview',input));page.querySelector('#connection-preview')!.innerHTML=`<form id="connection-activate" class="card"><h2>确认配置变更</h2>${summary(plan)}<p>新连接／尝试采用新版本。原窗口和 UNKNOWN 保留。当前消费者 ${connections.length} 个，准备失败保留原有效版本；决定后故障按原激活恢复。</p><label class="check"><input type="checkbox" required>确认激活这份完整候选</label><button>保存并激活</button></form>`;bind('#connection-activate',async()=>finishConfiguration(()=>configuration.start('/api/configuration/save',{...input,plan_digest:plan.plan_digest,reason:'管理员通信设置'})));});
  }else{
    area.innerHTML=`<section class="card"><h2>接入规范与示例</h2><p><a href="/protocol/http.json" download>HTTP OpenAPI</a> · <a href="/protocol/ws.json" download>WS JSON Schema</a> · <a href="/protocol/iris_client.py" download>Python WS 客户端</a> · <a href="/protocol/http_client.py" download>HTTP 命令行客户端</a> · <a href="/protocol/reconnect.py" download>重连辅助模块</a> · <a href="/protocol/event.json" download>接收输入示例</a> · <a href="/protocol/query.json" download>召回输入示例</a></p><p>三个 Python 文件放在同一目录，运行 python http_client.py --help 查看各操作和原确认用法。</p><p>凭据从环境注入，勿放 URL 或普通配置。客户端超时后按原键确认；UNKNOWN 不重发。WSS 使用受信任证书，代理空闲期限至少 60 秒。</p></section><form id="connection-browser" class="card"><h2>浏览器同源 WS 检查</h2>${selectRoutes()}<p>短时一次性票据仅可接收探针，不占用正式消费者路由。此检查不能证明外部宿主网络可达。</p><button>申请票据并认证</button></form><form id="connection-probe" class="card"><h2>显式合成探针</h2>${selectRoutes()}<label>接收方<select aria-label="接收方" name="target"><option value="host">真实在线宿主</option><option value="browser">本页测试连接</option></select></label><p>全局每分钟最多 3 次；无模型请求；专注期拒绝。刷新不会重发。</p><button>发送一次探针</button></form><ol id="connection-test-results" aria-live="polite"></ol>`;
    let browserId:string|undefined;const results=page.querySelector('#connection-test-results')!;
    const step=(s:string)=>{const li=document.createElement('li');li.textContent=s;results.append(li);};
    bind('#connection-browser',async f=>{closeConnectionPage();browserId=undefined;const issued=object(await api('/api/connections/tickets/create',{route_id:val(f,'route_id')}));step('受 CSRF 保护的票据已签发（30 秒）。');const socket=new WebSocket(String(overview.origin).replace(/^http/,'ws')+'/api/host/ws','iris.communication.v1');browserSocket=socket;socket.onopen=()=>{step('WS 握手成功，正在消费测试票据。');socket.send(JSON.stringify({version:1,type:'authenticate',request_id:crypto.randomUUID(),ticket:issued.ticket}));delete issued.ticket;};socket.onmessage=e=>{const msg=object(JSON.parse(String(e.data)));if(msg.type==='ready'){browserId=String(msg.connection_id);step('测试身份就绪，只允许探针。');}else if(msg.event==='connection.probe'){step('收到合成探针。');socket.send(JSON.stringify({version:1,type:'ack',route_id:msg.route_id,delivery_id:msg.delivery_id,status:'RECEIVED'}));}else step(JSON.stringify(msg));};socket.onclose=e=>step('测试连接关闭：'+e.code);socket.onerror=()=>step('WS 失败，请核对地址、TLS 和 Origin。');});
    bind('#connection-probe',async f=>{if(val(f,'target')==='browser'&&!browserId)throw new Error('请先完成本页测试身份认证。');const result=await write('connection.probe','/api/connections/probes/run',{route_id:val(f,'route_id'),connection_id:val(f,'target')==='browser'?browserId:null});const registered=object(result.registration);if(!registered.receipt){step('探针尚未确认登记，请保留当前输入并继续原操作。'+JSON.stringify(registered));return;}step('探针登记已确认：'+JSON.stringify(result));});
  }
  }finally{c.page.setAttribute('aria-busy','false');}
}
